//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAACE.eStaffing.Web.Pages.Administration {
    
    
    public partial class System {
        
        /// <summary>
        /// lkbResetCache control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lkbResetCache;
        
        /// <summary>
        /// ddlFormType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.DropDownControl ddlFormType;
        
        /// <summary>
        /// txtFormTypeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.TextControl txtFormTypeName;
        
        /// <summary>
        /// ddlSuspenseDateField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.DropDownControl ddlSuspenseDateField;
        
        /// <summary>
        /// ddlSubjectField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.DropDownControl ddlSubjectField;
        
        /// <summary>
        /// ddlFormNumberField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.DropDownControl ddlFormNumberField;
        
        /// <summary>
        /// ddlFormActionType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USAACE.Common.Web.Controls.DropDownControl ddlFormActionType;
        
        /// <summary>
        /// btnSaveFormType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnSaveFormType;
    }
}
