//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Contact> SortedContacts()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Contact> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.OrderBy(
                    this.GetQuery<global::LightSwitchApplication.Implementation.Contact>("Contacts"),
                    (c) => c.FirstName),
                (c) => c.LastName);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Contact> ContactsByBirthDate(global::System.Nullable<global::System.DateTime> MinimumBirthDate, global::System.Nullable<global::System.DateTime> MaximumBirthDate)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Contact> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Contact>("SortedContacts"),
                (c) => (((MinimumBirthDate.HasValue == false) || (c.BirthDate.HasValue && (MinimumBirthDate.HasValue && (c.BirthDate >= MinimumBirthDate)))) && ((MaximumBirthDate.HasValue == false) || (c.BirthDate.HasValue && (MaximumBirthDate.HasValue && (c.BirthDate <= MaximumBirthDate))))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.PhoneNumber> ContactsByPhone(string FindContact)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.PhoneNumber> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.ThenBy(
                    global::System.Linq.Queryable.OrderBy(
                        global::System.Linq.Queryable.Where(
                            this.GetQuery<global::LightSwitchApplication.Implementation.PhoneNumber>("PhoneNumbers"),
                            (p) => ((((FindContact == null) || p.Contact.LastName.Contains(FindContact)) || ((FindContact == null) || p.Contact.FirstName.Contains(FindContact))) || ((FindContact == null) || p.Phone.Contains(FindContact)))),
                        (p) => p.Contact.FirstName),
                    (p) => p.Contact.LastName),
                (p) => p.Phone);
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Contact))
            {
                return new global::LightSwitchApplication.Implementation.Contact();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmailAddress))
            {
                return new global::LightSwitchApplication.Implementation.EmailAddress();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.PhoneNumber))
            {
                return new global::LightSwitchApplication.Implementation.PhoneNumber();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Address))
            {
                return new global::LightSwitchApplication.Implementation.Address();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Contact))
            {
                return new global::LightSwitchApplication.Implementation.Contact();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmailAddress))
            {
                return new global::LightSwitchApplication.Implementation.EmailAddress();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PhoneNumber))
            {
                return new global::LightSwitchApplication.Implementation.PhoneNumber();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Address))
            {
                return new global::LightSwitchApplication.Implementation.Address();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Contact) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Contact);
            }
            if (typeof(global::LightSwitchApplication.EmailAddress) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmailAddress);
            }
            if (typeof(global::LightSwitchApplication.PhoneNumber) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PhoneNumber);
            }
            if (typeof(global::LightSwitchApplication.Address) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Address);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Contact :
        global::LightSwitchApplication.Contact.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Contact.DetailsClass.IImplementation.EmailAddresses
        {
            get
            {
                return this.EmailAddresses;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Contact.DetailsClass.IImplementation.PhoneNumbers
        {
            get
            {
                return this.PhoneNumbers;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Contact.DetailsClass.IImplementation.Addresses
        {
            get
            {
                return this.Addresses;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmailAddress :
        global::LightSwitchApplication.EmailAddress.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmailAddress.DetailsClass.IImplementation.Contact
        {
            get
            {
                return this.Contact;
            }
            set
            {
                this.Contact = (global::LightSwitchApplication.Implementation.Contact)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Contact");
                }
            }
        }
        
        partial void OnEmailAddress_ContactChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Contact");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PhoneNumber :
        global::LightSwitchApplication.PhoneNumber.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PhoneNumber.DetailsClass.IImplementation.Contact
        {
            get
            {
                return this.Contact;
            }
            set
            {
                this.Contact = (global::LightSwitchApplication.Implementation.Contact)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Contact");
                }
            }
        }
        
        partial void OnPhoneNumber_ContactChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Contact");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Address :
        global::LightSwitchApplication.Address.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Address.DetailsClass.IImplementation.Contact
        {
            get
            {
                return this.Contact;
            }
            set
            {
                this.Contact = (global::LightSwitchApplication.Implementation.Contact)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Contact");
                }
            }
        }
        
        partial void OnAddress_ContactChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Contact");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

